version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
  
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:password@db/todo_db
    ports:
      - "5000:5000"
